create table users (
    id bigint generated by default as identity, 
    password nvarchar(255), 
    role nvarchar(255), 
    username nvarchar(255), 
    primary key (id)
);

create table comment (
    id bigint generated by default as identity, 
    avatar nvarchar(255), 
    content nvarchar(4000), 
    name nvarchar(255), 
    occupation nvarchar(255), 
    primary key (id)
);

create table orders (
    id bigint generated by default as identity, 
    address varchar(255), 
    email varchar(255), 
    name varchar(255), 
    note varchar(255), 
    phone varchar(255), 
    status varchar(255), 
    primary key (id)
);

create table products (
    id bigint generated by default as identity, 
    category nvarchar(255), 
    discount double, 
    image nvarchar(255), 
    material nvarchar(255), 
    name nvarchar(255), 
    price double, 
    size nvarchar(255), 
    type nvarchar(255), 
    primary key (id)
);

insert into users (username, password, role) values ('admin', 'admin', 'admin');
insert into users (username, password, role) values ('user', 'user', 'user');
insert into users (username, password, role) values ('hanhoa', '123', 'user');

insert into products (name, price, discount, category, type, material, image, size) values (N'Áo khoác nam hai lớp', 380000, 280000, N'Thời trang nam', N'Áo khoác', N'Vải Wool-like', N'../../assets/images/ao-nam-1.jpg', N'XS, S, M, L, XL');
insert into products (name, price, discount, category, type, material, image, size) values (N'Áo khoác nam kaki', 480000, 420000, N'Thời trang nam', N'Áo khoác', N'Vải Kaki', N'../../assets/images/ao-nam-2.jpg', N'S');
insert into products (name, price, discount, category, type, material, image, size) values (N'Áo khoác nam quân đội', 260000, 190000, N'Thời trang nam', N'Áo khoác', N'Vải 100% Cotton', N'../../assets/images/ao-nam-3.jpg', N'XS, S');
insert into products (name, price, discount, category, type, material, image, size) values (N'Áo khoác nam thám hiểm classic quân đội', 350000, 300000, N'Thời trang nam', N'Áo khoác', N'Vải 50% Cotton, 50% Polyester cao cấp', N'../../assets/images/ao-nam-4.jpg', N'L, XL');
insert into products (name, price, discount, category, type, material, image, size) values (N'Áo Măng Tô Nam Dáng Dài Cổ Ve Tây Classic', 550000, 450000, N'Thời trang nam', N'Áo khoác', N'Dạ len cao cấp (80% wool, 20% polyester)', N'../../assets/images/ao-nam-5.jpg', N'M, L, XL');
insert into products (name, price, discount, category, type, material, image, size) values (N'Áo Măng Tô Nam Dáng Suông Cổ Vest Chéo Urban Line', 620000, 520000, N'Thời trang nam', N'Áo khoác', N'Vải dạ nỉ Hàn cao cấp (60% wool, 30% viscose, 10% spandex)', N'../../assets/images/ao-nam-6.jpg', N'L, XL');
insert into products (name, price, discount, category, type, material, image, size) values (N'Áo phong cách tím than lịch lãm', 250000, 220000, N'Thời trang nam', N'Áo khoác', N'Vải Cotton', N'../../assets/images/ao-nam-7.jpg', N'XS, S, M, L, XL');
insert into products (name, price, discount, category, type, material, image, size) values (N'Áo phong cách trắng thanh lịch', 250000, 220000, N'Thời trang nam', N'Áo khoác', N'Vải Cotton', N'../../assets/images/ao-nam-8.jpg', N'XS, S');
insert into products (name, price, discount, category, type, material, image, size) values (N'Áo nam hoodie phong cách thể thao', 3700000, 1690000, N'Thời trang nam', N'Áo khoác', N'Vải Wool-like', N'../../assets/images/ao-nam-9.jpg', N'XS, S, M, L, XL');
insert into products (name, price, discount, category, type, material, image, size) values (N'Áo nữ dễ thương', 150000, 99000, N'Thời trang nữ', N'Áo thun', N'Vải Cotton', N'../../assets/images/ao-nu-1.jpg', N'XS, S');
insert into products (name, price, discount, category, type, material, image, size) values (N'Áo nữ trẻ trung', 200000, 100000, N'Thời trang nữ', N'Áo thun', N'Vải Cotton', N'../../assets/images/ao-nu-2.jpg', N'XS, S, M, L, XL');
insert into products (name, price, discount, category, type, material, image, size) values (N'Áo nữ thanh lịch', 100000, 80000, N'Thời trang nữ', N'Áo thun', N'Vải 50% Cotton, 50% Polyester', N'../../assets/images/ao-nu-3.jpg', N'XS, S');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày tây nam', 3700000, 3490000, N'Thời trang nam', N'Giày', N'Da thật (Leather)', N'../../assets/images/giay-nam-1.jpg', N'39-44');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày cao gót sang trọng', 400000, 349000, N'Thời trang nữ', N'Giày', N'Da cao cấp', N'../../assets/images/giay-nu-1.jpg', N'35-40');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày cao gót quyến rũ', 400000, 399000, N'Thời trang nữ', N'Giày', N'Da cao cấp', N'../../assets/images/giay-nu-2.jpg', N'35-40');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày trẻ em cao cổ giữ ấm', 200000, 179000, N'Thời trang trẻ em', N'Giày', N'Vải Wool-like', N'../../assets/images/giay-tre-em-1.jpg', N'29-34');
insert into products (name, price, discount, category, type, material, image, size) values (N'Mũ cao bồi phong trần', 150000, 119000, N'Thời trang nam', N'Mũ', N'Vải Kaki', N'../../assets/images/mu-nam-1.jpg', N'XS, S, M, L, XL');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày tây nam đế cao', 450000, 350000, N'Thời trang nam', N'Giày', N'Da cao cấp', N'../../assets/images/shoe-1.jpg', N'39-44');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày tây nam thoáng khí', 500000, 430000, N'Thời trang nam', N'Giày', N'Da cao cấp', N'../../assets/images/shoe-2.jpg', N'39-44');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày tây nam đen cổ điển', 550000, 490000, N'Thời trang nam', N'Giày', N'Da cao cấp', N'../../assets/images/shoe-3.jpg', N'35-40');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày cao cổ nam du lịch', 620000, 550000, N'Thời trang nam', N'Giày', N'Vải canvas', N'../../assets/images/shoe-4.jpg', N'39-44');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày cao cổ nam thám hiểm', 620000, 520000, N'Thời trang nam', N'Giày', N'Vải canvas', N'../../assets/images/shoe-5.jpg', N'39-44');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày tây nam hoạ tiết', 420000, 320000, N'Thời trang nam', N'Giày', N'Da cao cấp', N'../../assets/images/shoe-6.jpg', N'39-44');
insert into products (name, price, discount, category, type, material, image, size) values (N'Áo thun co dãn', 120000, 100000, N'Thời trang trẻ em', N'Đồ bộ', N'Vải 100% Cotton', N'../../assets/images/shorts-1.jpg', N'XS, S, M, L, XL');
insert into products (name, price, discount, category, type, material, image, size) values (N'Quần thun co dãn', 120000, 100000, N'Thời trang trẻ em', N'Đồ bộ', N'Vải 100% Cotton', N'../../assets/images/shorts-2.jpg', N'XS, S, M, L, XL');
insert into products (name, price, discount, category, type, material, image, size) values (N'Thắt lưng da cao cấp', 420000, 340000, N'Thời trang nam', N'Thắt lưng', N'Da cao cấp', N'../../assets/images/that-lung.jpg', N'29-34');
insert into products (name, price, discount, category, type, material, image, size) values (N'Váy nữ công sở', 220000, 190000, N'Thời trang nữ', N'Váy', N'Vải 100% Cotton', N'../../assets/images/vay-nu-1.jpg', N'29-34');
insert into products (name, price, discount, category, type, material, image, size) values (N'Váy xoè nữ tính', 250000, 150000, N'Thời trang nữ', N'Váy', N'Vải 100% Cotton', N'../../assets/images/vay-nu-2.jpg', N'29-34');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày nam Runner Flex', 450000, 420000, N'Thời trang nam', N'Giày', N'Vải dệt Knit co giãn + Đế EVA nhẹ', N'../../assets/images/sports-1.jpg', N'39-44');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày nam Trail Beast', 470000, 419000, N'Thời trang nam', N'Giày', N'Vải canvas + Đế cao su đúc', N'../../assets/images/sports-2.jpg', N'39-44');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày nam Velocity Grip', 519000, 449000, N'Thời trang nam', N'Giày', N'Vải Ripstop chống rách + Đế cao su răng cưa', N'../../assets/images/sports-3.jpg', N'39-44');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày nam Urban Motion', 490000, 419000, N'Thời trang nam', N'Giày', N'Vải lưới dệt kỹ thuật + Đế đệm TPR', N'../../assets/images/sports-4.jpg', N'39-44');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày nam AeroLight Pro', 650000, 419000, N'Thời trang nam', N'Giày', N'Vải lưới Mesh + TPU bảo vệ gót', N'../../assets/images/sports-5.jpg', N'39-44');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày nam Street Core', 550000, 510000, N'Thời trang nam', N'Giày', N'Da tổng hợp PU + Đế cao su chống trượt', N'../../assets/images/sports-6.jpg', N'39-44');
insert into products (name, price, discount, category, type, material, image, size) values (N'Giày trẻ em cao cổ', 200000, 179000, N'Thời trang trẻ em', N'Giày', N'Vải Wool-like', N'../../assets/images/giay-tre-em-2.jpg', N'29-34');

insert into comment (name, avatar, occupation, content) values ('Nguyễn Thanh Hà', '../../assets/images/avatar1.jpg', 'Kỹ sư', 'Mình rất ấn tượng với bộ sưu tập đồ nam của shop – thiết kế trẻ trung, chất vải mát và form dáng chuẩn. Nhân viên tư vấn nhiệt tình, chắc chắn sẽ quay lại!');
insert into comment (name, avatar, occupation, content) values ('Nguyễn Huỳnh Đức', '../../assets/images/avatar2.jpg', 'Giáo viên', 'Shop có nhiều mẫu áo cực kỳ đẹp và sang, giá cả hợp lý. Mình rất thích không gian cửa hàng, rộng rãi và bày trí bắt mắt. Rất đáng để ghé thăm mỗi khi cần mua đồ!');
insert into comment (name, avatar, occupation, content) values ('Hàn Minh Hoà', '../../assets/images/avatar3.jpg', 'Sinh viên', 'Đồ trẻ em ở shop rất dễ thương, chất liệu mềm mại, an toàn cho bé. Mình mua cho con 2 bộ mà bé mặc rất thoải mái. Sẽ giới thiệu cho các mẹ bỉm khác!');
